version: "3"
services:
  radvent:
    build: app
    ports:
      - "3000:3000"
    environment:
      YEAR: "$YEAR"
      RAILS_ENV: "$RAILS_ENV"
    volumes:
      - ./app/config/database.yml:/usr/src/app/config/database.yml
      - ./app/config/constants.rb:/usr/src/app/config/initializers/constants.rb
      - ./data/app/log:/usr/src/app/log
      - ./data/app/db/data:/usr/src/app/db/data
      - ./data/app/public/uploads:/usr/src/app/public/uploads
    restart: always
  web:
    image: nginx:1.15.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/.htpasswd:/etc/nginx/.htpasswd
      - ./data/web/log:/var/log/nginx
    restart: always
